# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f729d263e3dc7c5e07ee007543d21b7d0d1eee1672b21adfd8c7352456704328bb274e3be26e5cdbef8bcb488a86bb6ae9977c30826a55ef02af7e8349daca3a

test:
  secret_key_base: 5c3c039d33b331e67640ada1620db7e1b1b1c1629c2fc9e10b9604a1b66d90518828ed86fc70289d2042aac8899543737dd4325dacf504dce49be17c395ec25e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
